#!/bin/bash

# Prints the current volume or 🔇 if muted.
[ $(pamixer --get-mute) = true ] && echo   && exit

# Get volume level.
vol="$(pamixer --get-volume)"

if [ "$vol" -gt "60" ]; then
	icon=" "
elif [ "$vol" -gt "30" ]; then
	icon=" "
elif [ "$vol" -gt "1" ]; then
	icon=" "
else
    icon=" "    echo   && exit
fi

echo "$icon$vol%"
# echo "$icon"
