"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_red1)\
$os\
$username\
[](bg:color_red2 fg:color_red1)\
$directory\
[](fg:color_red2 bg:color_red2)\
$git_branch\
$git_status\
[](fg:color_red2 bg:color_red3)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_red3 bg:color_red4)\
$docker_context\
$conda\
[](fg:color_red4 bg:color_blue)\
$time\
[ ](fg:color_blue)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_red1 = '#CC0000'
color_red2 = '#B30000'
color_red3 = '#990000'
color_red4 = '#800000'
color_blue = '#0093FA'
color_black= '#000000'
color_yellow = '#FFD901'

[os]
disabled = false
style = "bg:color_red1 fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
#Debian = "󰣚"
Debian = "󱢇"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_red1 fg:color_fg0"
style_root = "bg:color_red1 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_red2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_red2"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_red2)]($style)'

[git_status]
style = "bg:color_red2"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_red2)]($style)'

[nodejs]
symbol = ""
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[c]
symbol = " "
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[rust]
symbol = ""
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[golang]
symbol = ""
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[php]
symbol = ""
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[java]
symbol = " "
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[kotlin]
symbol = ""
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[haskell]
symbol = ""
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[python]
symbol = ""
style = "bg:color_red3"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red3)]($style)'

[docker_context]
symbol = ""
style = "bg:color_red3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_red3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_blue"
format = '[[  $time ](fg:color_black bg:color_blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_blue)'
error_symbol = '[](bold fg:color_red4)'
vimcmd_symbol = '[](bold fg:color_yellow)'
vimcmd_replace_one_symbol = '[](bold fg:color_blue)'
vimcmd_replace_symbol = '[](bold fg:color_blue)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
